import S from "@sanity/desk-tool/structure-builder";
import {
  HiOutlineCog,
  HiOutlineHome,
  HiOutlineIdentification,
  HiOutlineInformationCircle,
  HiOutlineStar,
  HiOutlineGlobe,
} from "react-icons/hi";

export default () =>
  S.list()
    .title("Inhalt")
    .items([
      S.listItem()
        .title("Einstellungen")
        .icon(HiOutlineCog)
        .child(
          S.list()
            .title("Einstellungen")
            .items([
              S.listItem()
                .title("Seite")
                .icon(HiOutlineInformationCircle)
                .child(
                  S.document()
                    .schemaType("siteSettings")
                    .documentId("siteSettings")
                ),
              S.documentTypeListItem("navigation").title("Navigation"),
              S.documentTypeListItem("category").title("Kategorien"),
              S.listItem()
                .title("Impressum")
                .icon(HiOutlineGlobe)
                .child(
                  S.document()
                    .schemaType("impressumPage")
                    .documentId("impressumPage")
                    .title("Impressum")
                ),
            ])
        ),
      S.divider(),
      S.listItem()
        .title("Startseite")
        .icon(HiOutlineHome)
        .child(
          S.document()
            .schemaType("indexPage")
            .documentId("indexPage")
            .title("Startseite")
        ),
      S.listItem()
        .title("Gastronomie")
        .icon(HiOutlineStar)
        .child(
          S.document()
            .schemaType("gastroPage")
            .documentId("gastroPage")
            .title("Gastronomie")
        ),
      S.listItem()
        .title("Kontaktseite")
        .icon(HiOutlineIdentification)
        .child(
          S.document()
            .schemaType("contactPage")
            .documentId("contactPage")
            .title("Kontakt")
        ),
      S.documentTypeListItem("page").title("Seiten"),
      S.documentTypeListItem("post").title("Neuigkeiten"),
      S.documentTypeListItem("report").title("Reports"),
      S.documentTypeListItem("download").title("Downloads"),
      S.divider(),
      S.documentTypeListItem("person").title("Personen"),
      S.documentTypeListItem("sponsor"),
    ]);
